name: Validate quick start module
on:
  pull_request:
    branches:
      site
    paths:
      - published_versions.json
      - assets/quick-start-module.js
      - .github/workflows/validate-quick-start-module.yml
  push:
    branches:
      site
    paths:
      - published_versions.json
      - assets/quick-start-module.js
      - .github/workflows/validate-quick-start-module.yml
  workflow_dispatch:

jobs:
  validate-nightly-binaries:
    uses: pytorch/test-infra/.github/workflows/validate-binaries.yml@main
    with:
      os: all
      channel: "nightly"
  validate-release-binaries:
    if: always()
    uses: pytorch/test-infra/.github/workflows/validate-binaries.yml@main
    needs: validate-nightly-binaries
    with:
      os: all
      channel: "release"
